-- Run this script inside the Supabase SQL Editor after creating a new project.
-- Supabase Auth is built in. If only pre-registered staff may log in,
-- disable public sign-ups in Auth > Providers > Email.

create extension if not exists pgcrypto;

create table if not exists public.customers (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default timezone('utc', now()),
    name text not null,
    phone_number text not null,
    notes_customer text not null default ''
);

create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default timezone('utc', now()),
    customer_id bigint not null references public.customers(id) on delete cascade,
    phone_number text not null,
    lens_kiri_speris numeric(6,2) not null default 0,
    lens_kanan_speris numeric(6,2) not null default 0,
    lens_kiri_addition numeric(6,2) not null default 0,
    lens_kanan_addition numeric(6,2) not null default 0,
    lens_kiri_cylinder numeric(6,2) not null default 0,
    lens_kanan_cylinder numeric(6,2) not null default 0,
    lens_kiri_axis numeric(6,2) not null default 0,
    lens_kanan_axis numeric(6,2) not null default 0,
    pupil_distance numeric(6,2) not null default 0,
    lens_price numeric(12,2) not null default 0,
    frame_price numeric(12,2) not null default 0,
    notes_transaction text not null default '',
    frame text not null default ''
);

create index if not exists customers_name_idx
    on public.customers (name);

create index if not exists customers_phone_number_idx
    on public.customers (phone_number);

create index if not exists transactions_customer_id_idx
    on public.transactions (customer_id);

create index if not exists transactions_phone_number_idx
    on public.transactions (phone_number);

alter table public.customers enable row level security;
alter table public.transactions enable row level security;

drop policy if exists "customers_select_authenticated" on public.customers;
create policy "customers_select_authenticated"
    on public.customers
    for select
    to authenticated
    using (true);

drop policy if exists "customers_insert_authenticated" on public.customers;
create policy "customers_insert_authenticated"
    on public.customers
    for insert
    to authenticated
    with check (true);

drop policy if exists "customers_update_authenticated" on public.customers;
create policy "customers_update_authenticated"
    on public.customers
    for update
    to authenticated
    using (true)
    with check (true);

drop policy if exists "customers_delete_authenticated" on public.customers;
create policy "customers_delete_authenticated"
    on public.customers
    for delete
    to authenticated
    using (true);

drop policy if exists "transactions_select_authenticated" on public.transactions;
create policy "transactions_select_authenticated"
    on public.transactions
    for select
    to authenticated
    using (true);

drop policy if exists "transactions_insert_authenticated" on public.transactions;
create policy "transactions_insert_authenticated"
    on public.transactions
    for insert
    to authenticated
    with check (true);

drop policy if exists "transactions_update_authenticated" on public.transactions;
create policy "transactions_update_authenticated"
    on public.transactions
    for update
    to authenticated
    using (true)
    with check (true);

drop policy if exists "transactions_delete_authenticated" on public.transactions;
create policy "transactions_delete_authenticated"
    on public.transactions
    for delete
    to authenticated
    using (true);

grant usage on schema public to anon, authenticated;
grant select on public.customers to authenticated;
grant insert, update, delete on public.customers to authenticated;
grant select on public.transactions to authenticated;
grant insert, update, delete on public.transactions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
